config/routes.rb
Rails.application.routes.draw do
  namespace :tasks do
    resource :wait, only: [:update]
  end
  resources :tasks
  resource :user, only: [:edit, :update], as: :my
  root 'tasks#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deleted_task.rb
class DeletedTask < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks, -> { order(deadline_at: :asc, created_at: :asc) }, dependent: :destroy

  validates :name, presence: true

  class << self
    def generate_default_lists!(user)
      # TODO: i18n対応は後から考える
      List.create!(name: '仕事', user: user)
      List.create!(name: '個人', user: user)
    end

    def build(params, current_user)
      list= List.new(params)
      list.user = current_user
      list
    end
  end
end

app/models/notification.rb
class Notification
  class << self
    def run
    end
  end
end

app/models/notifications/pushbullet.rb
module Notifications
  class Pushbullet
    TASK_TITLE = 'TaskMinder'.freeze
    class << self
      def run
        host = Rails.configuration.app["host"]
        # NOTE: start the server
        Net::HTTP.get(URI.parse(host))
        User.where(notification: true).each do |user|
          ::Pushbullet.api_token = user.raw_pushbullet_api_token
          devices = ::Pushbullet::Device.all

          devices.each do |device|
            Task.deadline_is_close(user).each do |task|
              device.push_link(TASK_TITLE, host, task.detail)
            end
          end
          ::Pushbullet.api_token = nil
        end
      end
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :detail, presence: true

  after_destroy :generate_deleted_task

  scope :deadline_is_close, -> (user, range_end = 1.hour.since) do
    where(deadline_at: [Time.current..range_end])
  end

  enum status: [:wait, :doing, :finished]

  class << self
    def build(params, current_user)
      task = Task.new(params)
      task.user = current_user
      task
    end

    def with_tag(tag)
      if tag
        where("tags @> ARRAY[?]::varchar[]", tag)
      else
        all
      end
    end
  end

  def generate_deleted_task
    attributes = self.attributes.except('id', 'created_at', 'updated_at')
    DeletedTask.create!(attributes)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy
  has_many :tasks, dependent: :destroy

  before_save :encrypt_api_token

  class << self
    def find_or_create_from_auth_hash(auth)
      find_by(provider: auth['provider'], uid: auth['uid']) ||
        create_with_omniauth!(auth)
    end

    def create_with_omniauth!(auth)
      user = create! do |u|
        u.provider = auth['provider']
        u.uid = auth['uid']
        u.email = auth['info']['email'].presence || ''
        u.name = acquire_name_from_auth_hash(auth)
      end
      List.generate_default_lists!(user)
      user
    end

    def acquire_name_from_auth_hash(auth)
      case auth['provider']
      when 'twitter', 'facebook'
        auth['info']['nickname'].presence || auth['info']['name']
      else
        auth['info']['name']
      end
    end
  end

  def update_if_needed!(auth)
    new_email = auth['info']['email']
    if new_email.present? && email != new_email
      self.email = new_email
    end

    new_name = User.acquire_name_from_auth_hash(auth)
    if new_name.present? && name != new_name
      self.name = new_name
    end
    save! if changed?
  end

  def encrypt_api_token
    if pushbullet_api_token_changed? && pushbullet_api_token.present?
      self.pushbullet_api_token = Rails.application.message_verifier(:pushbullet_api_token).generate(pushbullet_api_token)
    end
  end

  def raw_pushbullet_api_token
    Rails.application.message_verifier(:pushbullet_api_token).verify(pushbullet_api_token)
  end

  def maskd_pushbullet_api_token
    pushbullet_api_token.present? ? '************' : ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_logged_in

  helper_method :current_user, :logged_in?, :fluid?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def check_logged_in
    redirect_to login_path unless logged_in?
  end

  def fluid?
    defined?(@fluid) && @fluid
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_logged_in
  protect_from_forgery except: [:create]

  def new
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    @user.update_if_needed!(auth_hash)
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session.destroy
    redirect_to login_path
  end

  protected
    def auth_hash
      request.env['omniauth.auth']
    end
end

app/controllers/tasks/starts_controller.rb
class Tasks::StartsController < ApplicationController
  def update
    @task = current_user.tasks.find(params[:id])
    @task.doing!
    redirect_to tasks_url, notice: 'Task was successfully updated.'
  end
end

app/controllers/tasks/waits_controller.rb
class Tasks::WaitsController < ApplicationController
  def update
    @task = current_user.tasks.find(params[:id])
    @task.wait!
    redirect_to tasks_url, notice: 'Task was successfully updated.'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_tasks, only: [:index, :create, :edit, :update, :destroy]

  def index
    @fluid = true
    @task = Task.new
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.build(task_params, current_user)

    if @task.save
      redirect_to tasks_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    def set_task
      @task = current_user.tasks.find(params[:id])
    end

    def set_tasks
      @tasks = current_user.tasks.with_tag(params[:tag]).order(deadline_at: :ASC).order(id: :DESC)
    end

    def task_params
      params[:task][:tags] = params[:task][:tags].split(',') if params[:task][:tags]
      params.require(:task).permit(:detail, :deadline_at, :point, tags: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to edit_my_url, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private
    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:notification, :pushbullet_api_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title
      | TodoMinder
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'realod'
    link[rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"]
    link[rel="manifest" href="/manifest.json"]
    = javascript_include_tag 'application', 'data-turbolinks-track': 'realod'
    = csrf_meta_tags

  body
    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          a href="../" class="navbar-brand" TodoMinder
          button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main"
            #icon-bar
            #icon-bar
            #icon-bar
        .navbar-collapse-collapse id="navbar-main"
          ul.nav.navbar-nav
            - if logged_in?
              li.dropdown
                a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
                  | menu
                  span.caret
                ul.dropdown-menu role="menu"
                  li
                    = link_to 'settings', edit_my_path
                  li
                    = link_to 'logout', logout_path

    - if fluid?
      .container-fluid
        = yield
    - else
      .container
        = yield

app/views/tasks/_form.html.slim
.col-lg-12
  .well.bs-component
    = form_for @task, html: { class: 'form-horizontal' } do |f|
      - if @task.errors.any?
        #error_explanation
          h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
          ul
            - @task.errors.full_messages.each do |message|
              li = message

      fieldset
        .form-group
          = f.label :detail, class: 'col-lg-2 control-label'
          .col-lg-10
            = f.text_field :detail, class: 'form-control'
        .form-group
          = f.label :deadline_at, class: 'col-lg-2 control-label'
          .col-lg-10
            = f.datetime_field :deadline_at, class: 'from-control'
        .form-group
          = f.label :point, class: 'col-lg-2 control-label'
          .col-lg-10
            = f.select :point, options_for_select((1..9).to_a, selected: @task.point), { include_blank: true }, { class: 'form-control' }
        .form-group
          = f.label :tags, class: 'col-lg-2 control-label'
          = f.text_field :tags, class: 'form-control', data: { role: "tagsinput" }, value: @task.tags.try(:join, ',')
        .col-lg-10.col-lg-offset-2
          .form-group
            = f.submit class: 'btn btn-primary'

app/views/tasks/edit.html.slim
== render 'form'

app/views/tasks/finishes/show.html.slim
 h2
   | おわったことリスト
 .row
   - @lists.each do |list|
     .col-sm-3.bootcards-list
       .panel.panel-default
         .panel-heading.clearfix
           h3.panel-title.pull-left
             strong
               = list.name
         .list-group
           - list.tasks.each do |task|
             .list-group-item
               p.list-group-item-text
                 - if task.point
                   strong.text-warning
                     = "#{task.point}pt"
                 - if task.tags.present?
                   - task.tags.each do |tag|
                     span.label.label-success.label-list
                       small
                         = tag
                 span.pull-right
                   = l(task.deadline_at) if task.deadline_at
               h4.list-group-item-heading
                 = task.detail
                 br
                 = link_to tasks_wait_path(id: task.id), { title: 'タスクリストに戻す', class: 'text-primary', method: :patch } do
                   i.fa.fa-backward.task-icon
         .panel-footer.text-center

app/views/tasks/index.html.slim
h2
  | タスクリスト
  = link_to new_task_path, { class: "btn btn-primary btn-xs add-task" }
    i.fa.fa-plus
    | 追加
.row
  - @tasks.each do |task|
    .col-sm-2.bootcards-list
      .panel.panel-default
        .panel-heading.clearfix
          .panel-title.pull-left
            = l(task.deadline_at) if task.deadline_at
          .panel-title.pull-right
            - if task.point
              strong.text-warning
                = "#{task.point}pt"
        .list-group
          .list-group-item
            p.list-group-item-text
            h4.list-group-item-heading
              = link_to task.detail, edit_task_path(task)
              br
            - if task.tags.present?
              - task.tags.each do |tag|
                span.label.label-success.label-list
                  small
                    = link_to tag, tasks_url(tag: tag), { class: 'tag_link' }
        .panel-footer.text-center
            = link_to task, { data: { confirm: 'Are you sure?' }, class: 'text-danger', method: :delete, title: 'タスク削除' } do
              i.fa.fa-trash-o.task.task-icon
                | 削除

app/views/tasks/new.html.slim
h1 New task

== render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
p#notice = notice

p
  strong Detail:
  = @task.detail
p
  strong List:
  = @task.list
p
  strong User:
  = @task.user
p
  strong Deadline at:
  = @task.deadline_at
p
  strong Weighting:
  = @task.point

= link_to 'Edit', edit_task_path(@task)
'|
= link_to 'Back', tasks_path

app/views/users/edit.html.slim
.col-lg-12
  .well.bs-component
    = form_for @user, url: my_url, html: { class: 'form-horizontal'} do |f|
      - if @user.errors.any?
        #error_explanation
          h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
          ul
            - @user.errors.full_messages.each do |message|
              li = message

      fieldset
        legend
          | Setting
        .form-group
          = f.label :notification, class: 'col-lg-2 control-label'
          .col-lg-10
            = f.check_box :notification, class: 'form-control'
        .form-group
          = f.label :pushbullet_api_token, class: 'col-lg-2 control-label'
          .col-lg-10
            = f.text_field :pushbullet_api_token, class: 'form-control', value: @user.maskd_pushbullet_api_token
        .col-lg-10.col-lg-offset-2
          .form-group
            = f.submit class: 'btn btn-primary'